export const navLevels = [
  {
    "Employee Level": "A.1.1",
    Track: "A",
    Level: 1,
    Step: 1,
    "Career Phase": "Contributing Individually",
    Description: "Non Exempt Contributor ",
    "Base Pay": "$17.50 ",
    "New Equity Grant": 500,
    "Refresh Equity Grant": "0",
    "EPIC min %": "10%",
    "EPIC max %": "10%",
    "People Leader EPIC min%": "10%",
    "People Leader EPIC max%": "10%"
  },
  {
    "Employee Level": "A.1.2",
    Track: "A",
    Level: 1,
    Step: 2,
    "Career Phase": "Contributing Individually",
    Description: "Non Exempt Contributor ",
    "Base Pay": "$18.00 ",
    "New Equity Grant": 500,
    "Refresh Equity Grant": "0",
    "EPIC min %": "10%",
    "EPIC max %": "10%",
    "People Leader EPIC min%": "10%",
    "People Leader EPIC max%": "10%"
  },
  {
    "Employee Level": "A.1.3",
    Track: "A",
    Level: 1,
    Step: 3,
    "Career Phase": "Contributing Individually",
    Description: "Non Exempt Contributor ",
    "Base Pay": "$18.50 ",
    "New Equity Grant": 500,
    "Refresh Equity Grant": "0",
    "EPIC min %": "10%",
    "EPIC max %": "10%",
    "People Leader EPIC min%": "10%",
    "People Leader EPIC max%": "10%"
  },
  {
    "Employee Level": "A.1.4",
    Track: "A",
    Level: 1,
    Step: 4,
    "Career Phase": "Contributing Individually",
    Description: "Non Exempt Contributor ",
    "Base Pay": "$19.00 ",
    "New Equity Grant": 500,
    "Refresh Equity Grant": "0",
    "EPIC min %": "10%",
    "EPIC max %": "10%",
    "People Leader EPIC min%": "10%",
    "People Leader EPIC max%": "10%"
  },
  {
    "Employee Level": "A.2.1",
    Track: "A",
    Level: 2,
    Step: 1,
    "Career Phase": "Contributing Individually",
    Description: "Non Exempt Contributor ",
    "Base Pay": "$19.50 ",
    "New Equity Grant": 1000,
    "Refresh Equity Grant": "0-1000",
    "EPIC min %": "10%",
    "EPIC max %": "10%",
    "People Leader EPIC min%": "10%",
    "People Leader EPIC max%": "10%"
  },
  {
    "Employee Level": "A.2.2",
    Track: "A",
    Level: 2,
    Step: 2,
    "Career Phase": "Contributing Individually",
    Description: "Non Exempt Contributor ",
    "Base Pay": "$20.00 ",
    "New Equity Grant": 1000,
    "Refresh Equity Grant": "0-1000",
    "EPIC min %": "10%",
    "EPIC max %": "10%",
    "People Leader EPIC min%": "10%",
    "People Leader EPIC max%": "10%"
  },
  {
    "Employee Level": "A.2.3",
    Track: "A",
    Level: 2,
    Step: 3,
    "Career Phase": "Contributing Individually",
    Description: "Non Exempt Contributor ",
    "Base Pay": "$20.50 ",
    "New Equity Grant": 1000,
    "Refresh Equity Grant": "0-1000",
    "EPIC min %": "10%",
    "EPIC max %": "10%",
    "People Leader EPIC min%": "10%",
    "People Leader EPIC max%": "10%"
  },
  {
    "Employee Level": "A.3.1",
    Track: "A",
    Level: 3,
    Step: 1,
    "Career Phase": "Applying Expertise",
    Description: "Sr. NE ",
    "Base Pay": "$21.00 ",
    "New Equity Grant": 2000,
    "Refresh Equity Grant": "0-3000",
    "EPIC min %": "10%",
    "EPIC max %": "10%",
    "People Leader EPIC min%": "10%",
    "People Leader EPIC max%": "10%"
  },
  {
    "Employee Level": "A.3.2",
    Track: "A",
    Level: 3,
    Step: 2,
    "Career Phase": "Applying Expertise",
    Description: "Sr. NE ",
    "Base Pay": "$21.50 ",
    "New Equity Grant": 2000,
    "Refresh Equity Grant": "0-3000",
    "EPIC min %": "10%",
    "EPIC max %": "10%",
    "People Leader EPIC min%": "10%",
    "People Leader EPIC max%": "10%"
  },
  {
    "Employee Level": "A.3.3",
    Track: "A",
    Level: 3,
    Step: 3,
    "Career Phase": "Applying Expertise",
    Description: "Sr. NE ",
    "Base Pay": "$22.00 ",
    "New Equity Grant": 2000,
    "Refresh Equity Grant": "0-3000",
    "EPIC min %": "10%",
    "EPIC max %": "10%",
    "People Leader EPIC min%": "10%",
    "People Leader EPIC max%": "10%"
  },
  {
    "Employee Level": "A.4.1",
    Track: "A",
    Level: 4,
    Step: 1,
    "Career Phase": "Contributing Individually",
    Description: "Exempt Contributor ",
    "Base Pay": "$55,000.00 ",
    "New Equity Grant": 2000,
    "Refresh Equity Grant": "0-3000",
    "EPIC min %": "5%",
    "EPIC max %": "5%",
    "People Leader EPIC min%": "5%",
    "People Leader EPIC max%": "10%"
  },
  {
    "Employee Level": "A.4.2",
    Track: "A",
    Level: 4,
    Step: 2,
    "Career Phase": "Contributing Individually",
    Description: "Exempt Contributor ",
    "Base Pay": "$60,000.00 ",
    "New Equity Grant": 2000,
    "Refresh Equity Grant": "0-3000",
    "EPIC min %": "5%",
    "EPIC max %": "5%",
    "People Leader EPIC min%": "5%",
    "People Leader EPIC max%": "10%"
  },
  {
    "Employee Level": "A.4.3",
    Track: "A",
    Level: 4,
    Step: 3,
    "Career Phase": "Contributing Individually",
    Description: "Exempt Contributor ",
    "Base Pay": "$65,000.00 ",
    "New Equity Grant": 2000,
    "Refresh Equity Grant": "0-3000",
    "EPIC min %": "5%",
    "EPIC max %": "5%",
    "People Leader EPIC min%": "5%",
    "People Leader EPIC max%": "10%"
  },
  {
    "Employee Level": "A.5.1",
    Track: "A",
    Level: 5,
    Step: 1,
    "Career Phase": "Contributing Individually",
    Description: "Exempt Contributor ",
    "Base Pay": "$75,000.00 ",
    "New Equity Grant": 3000,
    "Refresh Equity Grant": "0-6000",
    "EPIC min %": "5%",
    "EPIC max %": "5%",
    "People Leader EPIC min%": "5%",
    "People Leader EPIC max%": "10%"
  },
  {
    "Employee Level": "A.5.2",
    Track: "A",
    Level: 5,
    Step: 2,
    "Career Phase": "Contributing Individually",
    Description: "Exempt Contributor ",
    "Base Pay": "$80,000.00 ",
    "New Equity Grant": 3000,
    "Refresh Equity Grant": "0-6000",
    "EPIC min %": "5%",
    "EPIC max %": "5%",
    "People Leader EPIC min%": "5%",
    "People Leader EPIC max%": "10%"
  },
  {
    "Employee Level": "A.5.3",
    Track: "A",
    Level: 5,
    Step: 3,
    "Career Phase": "Contributing Individually",
    Description: "Exempt Contributor ",
    "Base Pay": "$85,000.00 ",
    "New Equity Grant": 3000,
    "Refresh Equity Grant": "0-6000",
    "EPIC min %": "5%",
    "EPIC max %": "5%",
    "People Leader EPIC min%": "5%",
    "People Leader EPIC max%": "10%"
  },
  {
    "Employee Level": "A.6.1",
    Track: "A",
    Level: 6,
    Step: 1,
    "Career Phase": "Applying Expertise",
    Description: "Senior Contributor / Leadership",
    "Base Pay": "$95,000.00 ",
    "New Equity Grant": 5000,
    "Refresh Equity Grant": "0-15000",
    "EPIC min %": "5%",
    "EPIC max %": "10%",
    "People Leader EPIC min%": "8%",
    "People Leader EPIC max%": "15%"
  },
  {
    "Employee Level": "A.6.2",
    Track: "A",
    Level: 6,
    Step: 2,
    "Career Phase": "Applying Expertise",
    Description: "Senior Contributor / Leadership",
    "Base Pay": "$100,000.00 ",
    "New Equity Grant": 5000,
    "Refresh Equity Grant": "0-15000",
    "EPIC min %": "5%",
    "EPIC max %": "10%",
    "People Leader EPIC min%": "8%",
    "People Leader EPIC max%": "15%"
  },
  {
    "Employee Level": "A.6.3",
    Track: "A",
    Level: 6,
    Step: 3,
    "Career Phase": "Applying Expertise",
    Description: "Senior Contributor / Leadership",
    "Base Pay": "$110,000.00 ",
    "New Equity Grant": 5000,
    "Refresh Equity Grant": "0-15000",
    "EPIC min %": "5%",
    "EPIC max %": "10%",
    "People Leader EPIC min%": "8%",
    "People Leader EPIC max%": "15%"
  },
  {
    "Employee Level": "A.7.1",
    Track: "A",
    Level: 7,
    Step: 1,
    "Career Phase": "Applying Expertise",
    Description: "Senior Contributor / Leadership",
    "Base Pay": "$120,000.00 ",
    "New Equity Grant": 10000,
    "Refresh Equity Grant": "0-25000",
    "EPIC min %": "5%",
    "EPIC max %": "10%",
    "People Leader EPIC min%": "8%",
    "People Leader EPIC max%": "15%"
  },
  {
    "Employee Level": "A.7.2",
    Track: "A",
    Level: 7,
    Step: 2,
    "Career Phase": "Applying Expertise",
    Description: "Senior Contributor / Leadership",
    "Base Pay": "$125,000.00 ",
    "New Equity Grant": 10000,
    "Refresh Equity Grant": "0-25000",
    "EPIC min %": "5%",
    "EPIC max %": "10%",
    "People Leader EPIC min%": "8%",
    "People Leader EPIC max%": "15%"
  },
  {
    "Employee Level": "A.7.3",
    Track: "A",
    Level: 7,
    Step: 3,
    "Career Phase": "Applying Expertise",
    Description: "Senior Contributor / Leadership",
    "Base Pay": "$130,000.00 ",
    "New Equity Grant": 10000,
    "Refresh Equity Grant": "0-25000",
    "EPIC min %": "5%",
    "EPIC max %": "10%",
    "People Leader EPIC min%": "8%",
    "People Leader EPIC max%": "15%"
  },
  {
    "Employee Level": "A.7.4",
    Track: "A",
    Level: 7,
    Step: 4,
    "Career Phase": "Applying Expertise",
    Description: "Senior Contributor / Leadership",
    "Base Pay": "$135,000.00 ",
    "New Equity Grant": 10000,
    "Refresh Equity Grant": "0-25000",
    "EPIC min %": "5%",
    "EPIC max %": "10%",
    "People Leader EPIC min%": "8%",
    "People Leader EPIC max%": "15%"
  },
  {
    "Employee Level": "A.7.5",
    Track: "A",
    Level: 7,
    Step: 5,
    "Career Phase": "Contributing Through Others",
    Description: "Senior Contributor / Leadership",
    "Base Pay": "$145,000.00 ",
    "New Equity Grant": 10000,
    "Refresh Equity Grant": "0-25000",
    "EPIC min %": "5%",
    "EPIC max %": "10%",
    "People Leader EPIC min%": "8%",
    "People Leader EPIC max%": "15%"
  },
  {
    "Employee Level": "A.8.1",
    Track: "A",
    Level: 8,
    Step: 1,
    "Career Phase": "Contributing Through Others",
    Description: "Advanced Leadership ",
    "Base Pay": "$160,000.00 ",
    "New Equity Grant": 15000,
    "Refresh Equity Grant": "0-40000",
    "EPIC min %": "8%",
    "EPIC max %": "15%",
    "People Leader EPIC min%": "10%",
    "People Leader EPIC max%": "20%"
  },
  {
    "Employee Level": "A.8.2",
    Track: "A",
    Level: 8,
    Step: 2,
    "Career Phase": "Contributing Through Others",
    Description: "Advanced Leadership ",
    "Base Pay": "$165,000.00 ",
    "New Equity Grant": 15000,
    "Refresh Equity Grant": "0-40000",
    "EPIC min %": "8%",
    "EPIC max %": "15%",
    "People Leader EPIC min%": "10%",
    "People Leader EPIC max%": "20%"
  },
  {
    "Employee Level": "A.8.3",
    Track: "A",
    Level: 8,
    Step: 3,
    "Career Phase": "Contributing Through Others",
    Description: "Advanced Leadership ",
    "Base Pay": "$175,000.00 ",
    "New Equity Grant": 15000,
    "Refresh Equity Grant": "0-40000",
    "EPIC min %": "8%",
    "EPIC max %": "15%",
    "People Leader EPIC min%": "10%",
    "People Leader EPIC max%": "20%"
  },
  {
    "Employee Level": "A.8.4",
    Track: "A",
    Level: 8,
    Step: 4,
    "Career Phase": "Contributing Through Others",
    Description: "Advanced Leadership ",
    "Base Pay": "$180,000.00 ",
    "New Equity Grant": 15000,
    "Refresh Equity Grant": "0-40000",
    "EPIC min %": "8%",
    "EPIC max %": "15%",
    "People Leader EPIC min%": "10%",
    "People Leader EPIC max%": "20%"
  },
  {
    "Employee Level": "A.8.5",
    Track: "A",
    Level: 8,
    Step: 5,
    "Career Phase": "Contributing Through Others",
    Description: "Advanced Leadership ",
    "Base Pay": "$190,000.00 ",
    "New Equity Grant": 15000,
    "Refresh Equity Grant": "0-40000",
    "EPIC min %": "8%",
    "EPIC max %": "15%",
    "People Leader EPIC min%": "10%",
    "People Leader EPIC max%": "20%"
  },
  {
    "Employee Level": "A.9.1",
    Track: "A",
    Level: 9,
    Step: 1,
    "Career Phase": "Contributing Through Others",
    Description: "Advanced Leadership ",
    "Base Pay": "$195,000.00 ",
    "New Equity Grant": 20000,
    "Refresh Equity Grant": "0-60000",
    "EPIC min %": "8%",
    "EPIC max %": "15%",
    "People Leader EPIC min%": "10%",
    "People Leader EPIC max%": "20%"
  },
  {
    "Employee Level": "A.9.2",
    Track: "A",
    Level: 9,
    Step: 2,
    "Career Phase": "Contributing Through Others",
    Description: "Advanced Leadership ",
    "Base Pay": "$200,000.00 ",
    "New Equity Grant": 20000,
    "Refresh Equity Grant": "0-60000",
    "EPIC min %": "8%",
    "EPIC max %": "15%",
    "People Leader EPIC min%": "10%",
    "People Leader EPIC max%": "20%"
  },
  {
    "Employee Level": "A.9.3",
    Track: "A",
    Level: 9,
    Step: 3,
    "Career Phase": "Contributing Through Others",
    Description: "Advanced Leadership ",
    "Base Pay": "$210,000.00 ",
    "New Equity Grant": 20000,
    "Refresh Equity Grant": "0-60000",
    "EPIC min %": "8%",
    "EPIC max %": "15%",
    "People Leader EPIC min%": "10%",
    "People Leader EPIC max%": "20%"
  },
  {
    "Employee Level": "A.9.4",
    Track: "A",
    Level: 9,
    Step: 4,
    "Career Phase": "Contributing Through Others",
    Description: "Advanced Leadership ",
    "Base Pay": "$215,000.00 ",
    "New Equity Grant": 20000,
    "Refresh Equity Grant": "0-60000",
    "EPIC min %": "8%",
    "EPIC max %": "15%",
    "People Leader EPIC min%": "10%",
    "People Leader EPIC max%": "20%"
  },
  {
    "Employee Level": "A.9.5",
    Track: "A",
    Level: 9,
    Step: 5,
    "Career Phase": "Contributing Through Others",
    Description: "Advanced Leadership ",
    "Base Pay": "$225,000.00 ",
    "New Equity Grant": 20000,
    "Refresh Equity Grant": "0-60000",
    "EPIC min %": "8%",
    "EPIC max %": "15%",
    "People Leader EPIC min%": "10%",
    "People Leader EPIC max%": "20%"
  },
  {
    "Employee Level": "B.4.1",
    Track: "B",
    Level: 4,
    Step: 1,
    "Career Phase": "Contributing Individually",
    Description: "Exempt Contributor ",
    "Base Pay": "$80,000.00 ",
    "New Equity Grant": 2000,
    "Refresh Equity Grant": "0-3000",
    "EPIC min %": "5%",
    "EPIC max %": "5%",
    "People Leader EPIC min%": "5%",
    "People Leader EPIC max%": "10%"
  },
  {
    "Employee Level": "B.4.2",
    Track: "B",
    Level: 4,
    Step: 2,
    "Career Phase": "Contributing Individually",
    Description: "Exempt Contributor ",
    "Base Pay": "$85,000.00 ",
    "New Equity Grant": 2000,
    "Refresh Equity Grant": "0-3000",
    "EPIC min %": "5%",
    "EPIC max %": "5%",
    "People Leader EPIC min%": "5%",
    "People Leader EPIC max%": "10%"
  },
  {
    "Employee Level": "B.4.3",
    Track: "B",
    Level: 4,
    Step: 3,
    "Career Phase": "Contributing Individually",
    Description: "Exempt Contributor ",
    "Base Pay": "$90,000.00 ",
    "New Equity Grant": 2000,
    "Refresh Equity Grant": "0-3000",
    "EPIC min %": "5%",
    "EPIC max %": "5%",
    "People Leader EPIC min%": "5%",
    "People Leader EPIC max%": "10%"
  },
  {
    "Employee Level": "B.5.1",
    Track: "B",
    Level: 5,
    Step: 1,
    "Career Phase": "Contributing Individually",
    Description: "Exempt Contributor ",
    "Base Pay": "$100,000.00 ",
    "New Equity Grant": 3000,
    "Refresh Equity Grant": "0-6000",
    "EPIC min %": "5%",
    "EPIC max %": "5%",
    "People Leader EPIC min%": "5%",
    "People Leader EPIC max%": "10%"
  },
  {
    "Employee Level": "B.5.2",
    Track: "B",
    Level: 5,
    Step: 2,
    "Career Phase": "Contributing Individually",
    Description: "Exempt Contributor ",
    "Base Pay": "$105,000.00 ",
    "New Equity Grant": 3000,
    "Refresh Equity Grant": "0-6000",
    "EPIC min %": "5%",
    "EPIC max %": "5%",
    "People Leader EPIC min%": "5%",
    "People Leader EPIC max%": "10%"
  },
  {
    "Employee Level": "B.5.3",
    Track: "B",
    Level: 5,
    Step: 3,
    "Career Phase": "Contributing Individually",
    Description: "Exempt Contributor ",
    "Base Pay": "$115,000.00 ",
    "New Equity Grant": 3000,
    "Refresh Equity Grant": "0-6000",
    "EPIC min %": "5%",
    "EPIC max %": "5%",
    "People Leader EPIC min%": "5%",
    "People Leader EPIC max%": "10%"
  },
  {
    "Employee Level": "B.6.1",
    Track: "B",
    Level: 6,
    Step: 1,
    "Career Phase": "Applying Expertise",
    Description: "Senior Contributor / Leadership",
    "Base Pay": "$125,000.00 ",
    "New Equity Grant": 5000,
    "Refresh Equity Grant": "0-15000",
    "EPIC min %": "5%",
    "EPIC max %": "10%",
    "People Leader EPIC min%": "8%",
    "People Leader EPIC max%": "15%"
  },
  {
    "Employee Level": "B.6.2",
    Track: "B",
    Level: 6,
    Step: 2,
    "Career Phase": "Applying Expertise",
    Description: "Senior Contributor / Leadership",
    "Base Pay": "$130,000.00 ",
    "New Equity Grant": 5000,
    "Refresh Equity Grant": "0-15000",
    "EPIC min %": "5%",
    "EPIC max %": "10%",
    "People Leader EPIC min%": "8%",
    "People Leader EPIC max%": "15%"
  },
  {
    "Employee Level": "B.6.3",
    Track: "B",
    Level: 6,
    Step: 3,
    "Career Phase": "Applying Expertise",
    Description: "Senior Contributor / Leadership",
    "Base Pay": "$135,000.00 ",
    "New Equity Grant": 5000,
    "Refresh Equity Grant": "0-15000",
    "EPIC min %": "5%",
    "EPIC max %": "10%",
    "People Leader EPIC min%": "8%",
    "People Leader EPIC max%": "15%"
  },
  {
    "Employee Level": "B.7.1",
    Track: "B",
    Level: 7,
    Step: 1,
    "Career Phase": "Applying Expertise",
    Description: "Senior Contributor / Leadership",
    "Base Pay": "$145,000.00 ",
    "New Equity Grant": 10000,
    "Refresh Equity Grant": "0-25000",
    "EPIC min %": "5%",
    "EPIC max %": "10%",
    "People Leader EPIC min%": "8%",
    "People Leader EPIC max%": "15%"
  },
  {
    "Employee Level": "B.7.2",
    Track: "B",
    Level: 7,
    Step: 2,
    "Career Phase": "Applying Expertise",
    Description: "Senior Contributor / Leadership",
    "Base Pay": "$150,000.00 ",
    "New Equity Grant": 10000,
    "Refresh Equity Grant": "0-25000",
    "EPIC min %": "5%",
    "EPIC max %": "10%",
    "People Leader EPIC min%": "8%",
    "People Leader EPIC max%": "15%"
  },
  {
    "Employee Level": "B.7.3",
    Track: "B",
    Level: 7,
    Step: 3,
    "Career Phase": "Applying Expertise",
    Description: "Senior Contributor / Leadership",
    "Base Pay": "$155,000.00 ",
    "New Equity Grant": 10000,
    "Refresh Equity Grant": "0-25000",
    "EPIC min %": "5%",
    "EPIC max %": "10%",
    "People Leader EPIC min%": "8%",
    "People Leader EPIC max%": "15%"
  },
  {
    "Employee Level": "B.7.4",
    Track: "B",
    Level: 7,
    Step: 4,
    "Career Phase": "Applying Expertise",
    Description: "Senior Contributor / Leadership",
    "Base Pay": "$160,000.00 ",
    "New Equity Grant": 10000,
    "Refresh Equity Grant": "0-25000",
    "EPIC min %": "5%",
    "EPIC max %": "10%",
    "People Leader EPIC min%": "8%",
    "People Leader EPIC max%": "15%"
  },
  {
    "Employee Level": "B.7.5",
    Track: "B",
    Level: 7,
    Step: 5,
    "Career Phase": "Applying Expertise",
    Description: "Senior Contributor / Leadership",
    "Base Pay": "$170,000.00 ",
    "New Equity Grant": 10000,
    "Refresh Equity Grant": "0-25000",
    "EPIC min %": "5%",
    "EPIC max %": "10%",
    "People Leader EPIC min%": "8%",
    "People Leader EPIC max%": "15%"
  },
  {
    "Employee Level": "B.8.1",
    Track: "B",
    Level: 8,
    Step: 1,
    "Career Phase": "Contributing Through Others",
    Description: "Advanced Leadership ",
    "Base Pay": "$180,000.00 ",
    "New Equity Grant": 15000,
    "Refresh Equity Grant": "0-40000",
    "EPIC min %": "8%",
    "EPIC max %": "15%",
    "People Leader EPIC min%": "10%",
    "People Leader EPIC max%": "20%"
  },
  {
    "Employee Level": "B.8.2",
    Track: "B",
    Level: 8,
    Step: 2,
    "Career Phase": "Contributing Through Others",
    Description: "Advanced Leadership ",
    "Base Pay": "$185,000.00 ",
    "New Equity Grant": 15000,
    "Refresh Equity Grant": "0-40000",
    "EPIC min %": "8%",
    "EPIC max %": "15%",
    "People Leader EPIC min%": "10%",
    "People Leader EPIC max%": "20%"
  },
  {
    "Employee Level": "B.8.3",
    Track: "B",
    Level: 8,
    Step: 3,
    "Career Phase": "Contributing Through Others",
    Description: "Advanced Leadership ",
    "Base Pay": "$195,000.00 ",
    "New Equity Grant": 15000,
    "Refresh Equity Grant": "0-40000",
    "EPIC min %": "8%",
    "EPIC max %": "15%",
    "People Leader EPIC min%": "10%",
    "People Leader EPIC max%": "20%"
  },
  {
    "Employee Level": "B.8.4",
    Track: "B",
    Level: 8,
    Step: 4,
    "Career Phase": "Contributing Through Others",
    Description: "Advanced Leadership ",
    "Base Pay": "$200,000.00 ",
    "New Equity Grant": 15000,
    "Refresh Equity Grant": "0-40000",
    "EPIC min %": "8%",
    "EPIC max %": "15%",
    "People Leader EPIC min%": "10%",
    "People Leader EPIC max%": "20%"
  },
  {
    "Employee Level": "B.8.5",
    Track: "B",
    Level: 8,
    Step: 5,
    "Career Phase": "Contributing Through Others",
    Description: "Advanced Leadership ",
    "Base Pay": "$210,000.00 ",
    "New Equity Grant": 15000,
    "Refresh Equity Grant": "0-40000",
    "EPIC min %": "8%",
    "EPIC max %": "15%",
    "People Leader EPIC min%": "10%",
    "People Leader EPIC max%": "20%"
  },
  {
    "Employee Level": "B.9.1",
    Track: "B",
    Level: 9,
    Step: 1,
    "Career Phase": "Contributing Through Others",
    Description: "Advanced Leadership ",
    "Base Pay": "$220,000.00 ",
    "New Equity Grant": 20000,
    "Refresh Equity Grant": "0-60000",
    "EPIC min %": "8%",
    "EPIC max %": "15%",
    "People Leader EPIC min%": "10%",
    "People Leader EPIC max%": "20%"
  },
  {
    "Employee Level": "B.9.2",
    Track: "B",
    Level: 9,
    Step: 2,
    "Career Phase": "Contributing Through Others",
    Description: "Advanced Leadership ",
    "Base Pay": "$225,000.00 ",
    "New Equity Grant": 20000,
    "Refresh Equity Grant": "0-60000",
    "EPIC min %": "8%",
    "EPIC max %": "15%",
    "People Leader EPIC min%": "10%",
    "People Leader EPIC max%": "20%"
  },
  {
    "Employee Level": "B.9.3",
    Track: "B",
    Level: 9,
    Step: 3,
    "Career Phase": "Contributing Through Others",
    Description: "Advanced Leadership ",
    "Base Pay": "$235,000.00 ",
    "New Equity Grant": 20000,
    "Refresh Equity Grant": "0-60000",
    "EPIC min %": "8%",
    "EPIC max %": "15%",
    "People Leader EPIC min%": "10%",
    "People Leader EPIC max%": "20%"
  },
  {
    "Employee Level": "B.9.4",
    Track: "B",
    Level: 9,
    Step: 4,
    "Career Phase": "Contributing Through Others",
    Description: "Advanced Leadership ",
    "Base Pay": "$240,000.00 ",
    "New Equity Grant": 20000,
    "Refresh Equity Grant": "0-60000",
    "EPIC min %": "8%",
    "EPIC max %": "15%",
    "People Leader EPIC min%": "10%",
    "People Leader EPIC max%": "20%"
  },
  {
    "Employee Level": "B.9.5",
    Track: "B",
    Level: 9,
    Step: 5,
    "Career Phase": "Contributing Through Others",
    Description: "Advanced Leadership ",
    "Base Pay": "$250,000.00 ",
    "New Equity Grant": 20000,
    "Refresh Equity Grant": "0-60000",
    "EPIC min %": "8%",
    "EPIC max %": "15%",
    "People Leader EPIC min%": "10%",
    "People Leader EPIC max%": "20%"
  },
  {
    "Employee Level": "C.4.1",
    Track: "C",
    Level: 4,
    Step: 1,
    "Career Phase": "Contributing Individually",
    Description: "Exempt Contributor ",
    "Base Pay": "$50,000.00 ",
    "New Equity Grant": 2000,
    "Refresh Equity Grant": "0-3000",
    "EPIC min %": "",
    "EPIC max %": "",
    "People Leader EPIC min%": "",
    "People Leader EPIC max%": ""
  },
  {
    "Employee Level": "C.4.2",
    Track: "C",
    Level: 4,
    Step: 2,
    "Career Phase": "Contributing Individually",
    Description: "Exempt Contributor ",
    "Base Pay": "$50,000.00 ",
    "New Equity Grant": 2000,
    "Refresh Equity Grant": "0-3000",
    "EPIC min %": "",
    "EPIC max %": "",
    "People Leader EPIC min%": "",
    "People Leader EPIC max%": ""
  },
  {
    "Employee Level": "C.4.3",
    Track: "C",
    Level: 4,
    Step: 3,
    "Career Phase": "Contributing Individually",
    Description: "Exempt Contributor ",
    "Base Pay": "$50,000.00 ",
    "New Equity Grant": 2000,
    "Refresh Equity Grant": "0-3000",
    "EPIC min %": "",
    "EPIC max %": "",
    "People Leader EPIC min%": "",
    "People Leader EPIC max%": ""
  },
  {
    "Employee Level": "C.5.1",
    Track: "C",
    Level: 5,
    Step: 1,
    "Career Phase": "Contributing Individually",
    Description: "Exempt Contributor ",
    "Base Pay": "$60,000.00 ",
    "New Equity Grant": 3000,
    "Refresh Equity Grant": "0-6000",
    "EPIC min %": "",
    "EPIC max %": "",
    "People Leader EPIC min%": "",
    "People Leader EPIC max%": ""
  },
  {
    "Employee Level": "C.5.2",
    Track: "C",
    Level: 5,
    Step: 2,
    "Career Phase": "Contributing Individually",
    Description: "Exempt Contributor ",
    "Base Pay": "$60,000.00 ",
    "New Equity Grant": 3000,
    "Refresh Equity Grant": "0-6000",
    "EPIC min %": "",
    "EPIC max %": "",
    "People Leader EPIC min%": "",
    "People Leader EPIC max%": ""
  },
  {
    "Employee Level": "C.5.3",
    Track: "C",
    Level: 5,
    Step: 3,
    "Career Phase": "Contributing Individually",
    Description: "Exempt Contributor ",
    "Base Pay": "$60,000.00 ",
    "New Equity Grant": 3000,
    "Refresh Equity Grant": "0-6000",
    "EPIC min %": "",
    "EPIC max %": "",
    "People Leader EPIC min%": "",
    "People Leader EPIC max%": ""
  },
  {
    "Employee Level": "C.6.1",
    Track: "C",
    Level: 6,
    Step: 1,
    "Career Phase": "Applying Expertise",
    Description: "Senior Contributor / Leadership",
    "Base Pay": "$80,000.00 ",
    "New Equity Grant": 5000,
    "Refresh Equity Grant": "0-15000",
    "EPIC min %": "5%",
    "EPIC max %": "10%",
    "People Leader EPIC min%": "8%",
    "People Leader EPIC max%": "15%"
  },
  {
    "Employee Level": "C.6.2",
    Track: "C",
    Level: 6,
    Step: 2,
    "Career Phase": "Applying Expertise",
    Description: "Senior Contributor / Leadership",
    "Base Pay": "$85,000.00 ",
    "New Equity Grant": 5000,
    "Refresh Equity Grant": "0-15000",
    "EPIC min %": "5%",
    "EPIC max %": "10%",
    "People Leader EPIC min%": "8%",
    "People Leader EPIC max%": "15%"
  },
  {
    "Employee Level": "C.6.3",
    Track: "C",
    Level: 6,
    Step: 3,
    "Career Phase": "Applying Expertise",
    Description: "Senior Contributor / Leadership",
    "Base Pay": "$90,000.00 ",
    "New Equity Grant": 5000,
    "Refresh Equity Grant": "0-15000",
    "EPIC min %": "5%",
    "EPIC max %": "10%",
    "People Leader EPIC min%": "8%",
    "People Leader EPIC max%": "15%"
  },
  {
    "Employee Level": "C.7.1",
    Track: "C",
    Level: 7,
    Step: 1,
    "Career Phase": "Applying Expertise",
    Description: "Senior Contributor / Leadership",
    "Base Pay": "$100,000.00 ",
    "New Equity Grant": 10000,
    "Refresh Equity Grant": "0-25000",
    "EPIC min %": "5%",
    "EPIC max %": "10%",
    "People Leader EPIC min%": "8%",
    "People Leader EPIC max%": "15%"
  },
  {
    "Employee Level": "C.7.2",
    Track: "C",
    Level: 7,
    Step: 2,
    "Career Phase": "Applying Expertise",
    Description: "Senior Contributor / Leadership",
    "Base Pay": "$105,000.00 ",
    "New Equity Grant": 10000,
    "Refresh Equity Grant": "0-25000",
    "EPIC min %": "5%",
    "EPIC max %": "10%",
    "People Leader EPIC min%": "8%",
    "People Leader EPIC max%": "15%"
  },
  {
    "Employee Level": "C.7.3",
    Track: "C",
    Level: 7,
    Step: 3,
    "Career Phase": "Applying Expertise",
    Description: "Senior Contributor / Leadership",
    "Base Pay": "$110,000.00 ",
    "New Equity Grant": 10000,
    "Refresh Equity Grant": "0-25000",
    "EPIC min %": "5%",
    "EPIC max %": "10%",
    "People Leader EPIC min%": "8%",
    "People Leader EPIC max%": "15%"
  },
  {
    "Employee Level": "C.7.4",
    Track: "C",
    Level: 7,
    Step: 4,
    "Career Phase": "Applying Expertise",
    Description: "Senior Contributor / Leadership",
    "Base Pay": "$115,000.00 ",
    "New Equity Grant": 10000,
    "Refresh Equity Grant": "0-25000",
    "EPIC min %": "5%",
    "EPIC max %": "10%",
    "People Leader EPIC min%": "8%",
    "People Leader EPIC max%": "15%"
  },
  {
    "Employee Level": "C.7.5",
    Track: "C",
    Level: 7,
    Step: 5,
    "Career Phase": "Applying Expertise",
    Description: "Senior Contributor / Leadership",
    "Base Pay": "$120,000.00 ",
    "New Equity Grant": 10000,
    "Refresh Equity Grant": "0-25000",
    "EPIC min %": "5%",
    "EPIC max %": "10%",
    "People Leader EPIC min%": "8%",
    "People Leader EPIC max%": "15%"
  },
  {
    "Employee Level": "C.8.1",
    Track: "C",
    Level: 8,
    Step: 1,
    "Career Phase": "Contributing Through Others",
    Description: "Advanced Leadership ",
    "Base Pay": "$160,000.00 ",
    "New Equity Grant": 15000,
    "Refresh Equity Grant": "0-40000",
    "EPIC min %": "8%",
    "EPIC max %": "15%",
    "People Leader EPIC min%": "10%",
    "People Leader EPIC max%": "20%"
  },
  {
    "Employee Level": "C.8.2",
    Track: "C",
    Level: 8,
    Step: 2,
    "Career Phase": "Contributing Through Others",
    Description: "Advanced Leadership ",
    "Base Pay": "$170,000.00 ",
    "New Equity Grant": 15000,
    "Refresh Equity Grant": "0-40000",
    "EPIC min %": "8%",
    "EPIC max %": "15%",
    "People Leader EPIC min%": "10%",
    "People Leader EPIC max%": "20%"
  },
  {
    "Employee Level": "C.8.3",
    Track: "C",
    Level: 8,
    Step: 3,
    "Career Phase": "Contributing Through Others",
    Description: "Advanced Leadership ",
    "Base Pay": "$180,000.00 ",
    "New Equity Grant": 15000,
    "Refresh Equity Grant": "0-40000",
    "EPIC min %": "8%",
    "EPIC max %": "15%",
    "People Leader EPIC min%": "10%",
    "People Leader EPIC max%": "20%"
  },
  {
    "Employee Level": "C.8.4",
    Track: "C",
    Level: 8,
    Step: 4,
    "Career Phase": "Contributing Through Others",
    Description: "Advanced Leadership ",
    "Base Pay": "$190,000.00 ",
    "New Equity Grant": 15000,
    "Refresh Equity Grant": "0-40000",
    "EPIC min %": "8%",
    "EPIC max %": "15%",
    "People Leader EPIC min%": "10%",
    "People Leader EPIC max%": "20%"
  },
  {
    "Employee Level": "C.8.5",
    Track: "C",
    Level: 8,
    Step: 5,
    "Career Phase": "Contributing Through Others",
    Description: "Advanced Leadership ",
    "Base Pay": "$200,000.00 ",
    "New Equity Grant": 15000,
    "Refresh Equity Grant": "0-40000",
    "EPIC min %": "8%",
    "EPIC max %": "15%",
    "People Leader EPIC min%": "10%",
    "People Leader EPIC max%": "20%"
  },
  {
    "Employee Level": "C.9.1",
    Track: "C",
    Level: 9,
    Step: 1,
    "Career Phase": "Contributing Through Others",
    Description: "Advanced Leadership ",
    "Base Pay": "$205,000.00 ",
    "New Equity Grant": 20000,
    "Refresh Equity Grant": "0-60000",
    "EPIC min %": "8%",
    "EPIC max %": "15%",
    "People Leader EPIC min%": "10%",
    "People Leader EPIC max%": "20%"
  },
  {
    "Employee Level": "C.9.2",
    Track: "C",
    Level: 9,
    Step: 2,
    "Career Phase": "Contributing Through Others",
    Description: "Advanced Leadership ",
    "Base Pay": "$210,000.00 ",
    "New Equity Grant": 20000,
    "Refresh Equity Grant": "0-60000",
    "EPIC min %": "8%",
    "EPIC max %": "15%",
    "People Leader EPIC min%": "10%",
    "People Leader EPIC max%": "20%"
  },
  {
    "Employee Level": "C.9.3",
    Track: "C",
    Level: 9,
    Step: 3,
    "Career Phase": "Contributing Through Others",
    Description: "Advanced Leadership ",
    "Base Pay": "$215,000.00 ",
    "New Equity Grant": 20000,
    "Refresh Equity Grant": "0-60000",
    "EPIC min %": "8%",
    "EPIC max %": "15%",
    "People Leader EPIC min%": "10%",
    "People Leader EPIC max%": "20%"
  },
  {
    "Employee Level": "C.9.4",
    Track: "C",
    Level: 9,
    Step: 4,
    "Career Phase": "Contributing Through Others",
    Description: "Advanced Leadership ",
    "Base Pay": "$220,000.00 ",
    "New Equity Grant": 20000,
    "Refresh Equity Grant": "0-60000",
    "EPIC min %": "8%",
    "EPIC max %": "15%",
    "People Leader EPIC min%": "10%",
    "People Leader EPIC max%": "20%"
  },
  {
    "Employee Level": "C.9.5",
    Track: "C",
    Level: 9,
    Step: 5,
    "Career Phase": "Contributing Through Others",
    Description: "Advanced Leadership ",
    "Base Pay": "$225,000.00 ",
    "New Equity Grant": 20000,
    "Refresh Equity Grant": "0-60000",
    "EPIC min %": "8%",
    "EPIC max %": "15%",
    "People Leader EPIC min%": "10%",
    "People Leader EPIC max%": "20%"
  }
];

export default navLevels;
